Traceback (most recent call last):
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/ccia/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load data: UTSC air temperature data for the years 2015-2018. in deg C. Data are collected hourly.
filename = 'UTSC_TC_20152018.csv'
X = np.genfromtxt(filename, delimiter = ',')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;66;03m# load data: UTSC air temperature data for the years 2015-2018. in deg C. Data are collected hourly.[39;00m
[1;32m      2[0m filename [38;5;241m=[39m [38;5;124m'[39m[38;5;124mUTSC_TC_20152018.csv[39m[38;5;124m'[39m
[0;32m----> 3[0m X [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mgenfromtxt[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mdelimiter[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m,[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/numpy/lib/npyio.py:1934[0m, in [0;36mgenfromtxt[0;34m(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, ndmin, like)[0m
[1;32m   1932[0m     fname [38;5;241m=[39m os_fspath(fname)
[1;32m   1933[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m):
[0;32m-> 1934[0m     fid [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlib[49m[38;5;241;43m.[39;49m[43m_datasource[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrt[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m)[49m
[1;32m   1935[0m     fid_ctx [38;5;241m=[39m contextlib[38;5;241m.[39mclosing(fid)
[1;32m   1936[0m [38;5;28;01melse[39;00m:

File [0;32m/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/numpy/lib/_datasource.py:193[0m, in [0;36mopen[0;34m(path, mode, destpath, encoding, newline)[0m
[1;32m    156[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    157[0m [38;5;124;03mOpen `path` with `mode` and return the file object.[39;00m
[1;32m    158[0m 
[0;32m   (...)[0m
[1;32m    189[0m 
[1;32m    190[0m [38;5;124;03m"""[39;00m
[1;32m    192[0m ds [38;5;241m=[39m DataSource(destpath)
[0;32m--> 193[0m [38;5;28;01mreturn[39;00m [43mds[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m,[49m[43m [49m[43mnewline[49m[38;5;241;43m=[39;49m[43mnewline[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/numpy/lib/_datasource.py:533[0m, in [0;36mDataSource.open[0;34m(self, path, mode, encoding, newline)[0m
[1;32m    530[0m     [38;5;28;01mreturn[39;00m _file_openers[ext](found, mode[38;5;241m=[39mmode,
[1;32m    531[0m                               encoding[38;5;241m=[39mencoding, newline[38;5;241m=[39mnewline)
[1;32m    532[0m [38;5;28;01melse[39;00m:
[0;32m--> 533[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m not found.[39m[38;5;124m"[39m)

[0;31mFileNotFoundError[0m: UTSC_TC_20152018.csv not found.
FileNotFoundError: UTSC_TC_20152018.csv not found.

