Traceback (most recent call last):
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/Karen/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
k = 1 # see what happends when you change wavenumber to the following values (1, 3, 5, 7, 10)

# initialize figure
plt.figure(figsize=(16,4))
plt.xlim(np.min(t),np.max(t))
plt.ylim(-1.3,1.3)
plt.xlabel('time')
plt.title('Nyquist cutoff: 5 total waves, 1 per 2 time steps')
plt.grid()

# define cosine wave using high-frequency t: this will be our "true" cosine wave
yh = np.cos(2.*np.pi*k*t/T)

# plot true cosine wave
plt.plot(t,yh,'--',color = 'red', linewidth = 1.,label='True Cosine Wave')

#define harmonics using low-frequency t
yl = np.cos(2.*np.pi*k*tl/T)

plt.plot(t1,yl,'.',color = 'blue',markersize = 20)
plt.plot(t1,yl,'-',color = 'blue', linewidth = 1.,label='Sampled Cosine Wave')
plt.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-9b6d31b14bc7>[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0myl[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mcos[0m[0;34m([0m[0;36m2.[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m*[0m[0mk[0m[0;34m*[0m[0mtl[0m[0;34m/[0m[0mT[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m [0;34m[0m[0m
[0;32m---> 20[0;31m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mt1[0m[0;34m,[0m[0myl[0m[0;34m,[0m[0;34m'.'[0m[0;34m,[0m[0mcolor[0m [0;34m=[0m [0;34m'blue'[0m[0;34m,[0m[0mmarkersize[0m [0;34m=[0m [0;36m20[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mt1[0m[0;34m,[0m[0myl[0m[0;34m,[0m[0;34m'-'[0m[0;34m,[0m[0mcolor[0m [0;34m=[0m [0;34m'blue'[0m[0;34m,[0m [0mlinewidth[0m [0;34m=[0m [0;36m1.[0m[0;34m,[0m[0mlabel[0m[0;34m=[0m[0;34m'Sampled Cosine Wave'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m [0mplt[0m[0;34m.[0m[0mlegend[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 't1' is not defined
NameError: name 't1' is not defined

